drop table page_views;

drop table page_typography;


drop table page_styles;
drop table page_scripts;
drop table password_resets;
drop table news_typography;
drop table news_styles;
drop table news_scripts;
drop table access_levels;
drop table activity_log;
drop table chats;
drop table csp_entries;
drop table draft_pages;
drop table draft_posts;
drop table emails;
drop table event_scripts;
drop table event_styles;
drop table event_typography;
drop table failed_jobs;
drop table faqs;
drop table faq_categories;
drop table gallery_item_tags;
drop table gallery_tags;
drop table gallery_items;
drop table galleries;
drop table fragments;
drop table media;
drop table menu_dropdown_items;
drop table menu_items;
drop table post_scripts;
drop table post_styles;
drop table post_typography;
drop table power_sports;
drop table migrations;
drop table slider_details;
drop table sliders;
drop table telescope_entries_tags;
drop table telescope_entries;
drop table telescope_monitoring;
drop table posts;
drop table blogs;
drop table calendar_events;
drop table news;
drop table pages;
drop table sections;
drop table recovery_codes;
drop table site_visitors;
drop table templates;
drop table user_histories;
drop table menus;
drop table preferences;
drop table transactions;
drop table user_roles;
drop table user_scripts;
drop table user_prefs;
drop table snippet_assets;
drop table users;
drop table login_types;
rename table videos to videos_old;
drop table roles;
alter table vehicle_videos drop foreign key vehicle_videos_video_id_foreign;
alter table videos_old drop foreign key videos_video_categories_id_foreign;
